2016-10-10 17:19:08:execute_script: /Users/tylan/Desktop/myAuty/Auty/scripts/scripts/__init__.py
2016-10-10 17:19:08:No exception in execute_script method.
2016-10-10 17:19:08:execute_script: /Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/follow_test.py
2016-10-10 17:19:09:No exception in execute_script method.
2016-10-10 17:19:09:execute_script: /Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/send_post_test.py
2016-10-10 17:19:10:No exception in execute_script method.
2016-10-10 17:19:10:execute_script: /Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/upload_images_test.py
2016-10-10 17:19:10:No exception in execute_script method.
2016-10-10 17:31:46:Exception in execute_script method: [Errno 2] No such file or directory: '/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/__init__.py'
2016-10-10 17:31:46:execute_script: /Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/follow_test.py
2016-10-10 17:31:47:No exception in execute_script method.
2016-10-10 17:31:47:execute_script: /Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/send_post_test.py
2016-10-10 17:31:48:No exception in execute_script method.
2016-10-10 17:31:48:execute_script: /Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/upload_images_test.py
2016-10-10 17:31:49:No exception in execute_script method.
