scriptPath,detail,startTime,endTime,duration,result
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/update_user_avatar_test.py,No exception in execute_script method.,2016-10-11 21:49:16.806150,2016-10-11 21:49:17.051302,0.24515199999999998,"Traceback (most recent call last):
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/update_user_avatar_test.py"", line 36, in <module>
    r,userId = get_red_users_test('runcheck5@163.com',avatarUrl)
NameError: name 'get_red_users_test' is not defined
"
,Exception in execute_script method: [Errno 2] No such file or directory: '',2016-10-11 21:49:17.051436,2016-10-11 21:49:17.051583,0.000147,
