scriptPath,detail,startTime,endTime,duration,result
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/batch_follow_test.py,No exception in execute_script method.,2016-10-10 22:24:45.095361,2016-10-10 22:24:45.751068,0.6557069999999999,"passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py,No exception in execute_script method.,2016-10-10 22:24:45.751177,2016-10-10 22:24:46.828118,0.076941,"{""result"":100,""resultDesc"":""收藏成功!"",""collectStatus"":""1""}
failed
passed
passed
{""result"":100,""resultDesc"":""取消收藏!"",""collectStatus"":""0""}
failed
passed
Traceback (most recent call last):
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py"", line 42, in <module>
    uncollect_assert(collect_post_test('runcheck5@163.com','1132664','0'))
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py"", line 38, in uncollect_assert
    tylan_assert(collectStatus,'0')
NameError: global name 'collectStatus' is not defined
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/follow_test.py,No exception in execute_script method.,2016-10-10 22:24:46.828218,2016-10-10 22:24:47.880032,0.051814,"passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/login_test.py,No exception in execute_script method.,2016-10-10 22:24:47.880128,2016-10-10 22:24:48.013744,0.13361599999999998,"No login interface.
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/post_info_test.py,No exception in execute_script method.,2016-10-10 22:24:48.013842,2016-10-10 22:24:48.622307,0.6084649999999999,"passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/report_test.py,No exception in execute_script method.,2016-10-10 22:24:48.622399,2016-10-10 22:24:48.834889,0.21248999999999998,"passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/search_users_test.py,No exception in execute_script method.,2016-10-10 22:24:48.834994,2016-10-10 22:24:49.844300,0.009306,"passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/send_post_test.py,No exception in execute_script method.,2016-10-10 22:24:49.844407,2016-10-10 22:24:50.954166,0.109759,"failed
failed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/upload_images_test.py,No exception in execute_script method.,2016-10-10 22:24:50.954287,2016-10-10 22:24:51.560149,0.605862,"passed
passed
"
