scriptPath,detail,startTime,endTime,duration,result
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_user_flower_cnt_test.py,No exception in execute_script method.,2016-10-11 22:45:03.129583,2016-10-11 22:45:06.225009,0.095426,"Traceback (most recent call last):
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_user_flower_cnt_test.py"", line 32, in <module>
    basic_assert(get_user_flower_cnt_test('runcheck5@163.com'))
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_user_flower_cnt_test.py"", line 21, in get_user_flower_cnt_test
    flowerCnt = get_lottery_user_flowers_cnt(accountId)
  File ""/Users/tylan/Desktop/myAuty/Auty/utils/get_lottery_user_flowers_cnt.py"", line 9, in get_lottery_user_flowers_cnt
    return r[0][3]
IndexError: tuple index out of range
"
,Exception in execute_script method: [Errno 2] No such file or directory: '',2016-10-11 22:45:06.225181,2016-10-11 22:45:06.225620,0.000439,
