scriptPath,detail,startTime,endTime,duration,result
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/update_user_avatar_test.py,No exception in execute_script method.,2016-10-11 21:49:31.045228,2016-10-11 21:49:31.684092,0.638864,"<html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
/circle_updateUserAvatar.html was not found on this server.
<p /><hr />
<small>
Resin/3.1.14
</small>
</body></html>

Traceback (most recent call last):
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/update_user_avatar_test.py"", line 37, in <module>
    basic_assert(r,userId)
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/update_user_avatar_test.py"", line 30, in basic_assert
    jsonResult = json.loads(r.content)
  File ""/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py"", line 338, in loads
    return _default_decoder.decode(s)
  File ""/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py"", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ""/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py"", line 384, in raw_decode
    raise ValueError(""No JSON object could be decoded"")
ValueError: No JSON object could be decoded
"
,Exception in execute_script method: [Errno 2] No such file or directory: '',2016-10-11 21:49:31.684235,2016-10-11 21:49:31.684341,0.000106,
