scriptPath,detail,startTime,endTime,duration,result
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/batch_follow_test.py,No exception in execute_script method.,2016-10-10 22:26:42.506015,2016-10-10 22:26:43.166541,0.660526,"passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py,No exception in execute_script method.,2016-10-10 22:26:43.166646,2016-10-10 22:26:43.788230,0.621584,"{""result"":100,""resultDesc"":""收藏成功!"",""collectStatus"":""1""}
Traceback (most recent call last):
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py"", line 41, in <module>
    collect_assert(collect_post_test('runcheck5@163.com','1132664','1'))
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py"", line 30, in collect_assert
    tylan_assert(jsonResult['resultDesc'],u""成功"")
  File ""/Users/tylan/Desktop/myAuty/Auty/utils/utils.py"", line 17, in tylan_assert
    print 'failed,actual result:'+str(actual)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/follow_test.py,No exception in execute_script method.,2016-10-10 22:26:43.788341,2016-10-10 22:26:44.871116,0.082775,"passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/login_test.py,No exception in execute_script method.,2016-10-10 22:26:44.871230,2016-10-10 22:26:45.006069,0.134839,"No login interface.
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/post_info_test.py,No exception in execute_script method.,2016-10-10 22:26:45.006175,2016-10-10 22:26:45.653102,0.6469269999999999,"passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/report_test.py,No exception in execute_script method.,2016-10-10 22:26:45.653261,2016-10-10 22:26:45.867645,0.214384,"passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/search_users_test.py,No exception in execute_script method.,2016-10-10 22:26:45.867747,2016-10-10 22:26:46.441140,0.5733929999999999,"passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/send_post_test.py,No exception in execute_script method.,2016-10-10 22:26:46.441234,2016-10-10 22:26:47.026314,0.5850799999999999,"Traceback (most recent call last):
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/send_post_test.py"", line 36, in <module>
    basic_assert(send_post_test('runcheck5@163.com'))
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/send_post_test.py"", line 32, in basic_assert
    tylan_assert(jsonResult['resultDesc'],u""发帖成功!"")
  File ""/Users/tylan/Desktop/myAuty/Auty/utils/utils.py"", line 17, in tylan_assert
    print 'failed,actual result:'+str(actual)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/upload_images_test.py,No exception in execute_script method.,2016-10-10 22:26:47.026416,2016-10-10 22:26:48.564824,0.538408,"passed
passed
"
