scriptPath,detail,startTime,endTime,duration,result
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_messages_test.py,No exception in execute_script method.,2016-10-11 21:06:27.672770,2016-10-11 21:06:28.354260,0.6814899999999999,"{""result"":100,""messages"":[],""resultDesc"":""成功""}
Traceback (most recent call last):
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_messages_test.py"", line 34, in <module>
    r,userId = get_messages_test('runcheck5@163.com')
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_messages_test.py"", line 25, in get_messages_test
    return r,userId
NameError: global name 'userId' is not defined
"
,Exception in execute_script method: [Errno 2] No such file or directory: '',2016-10-11 21:06:28.354411,2016-10-11 21:06:28.354921,0.0005099999999999999,
