scriptPath,detail,startTime,endTime,duration,result
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/batch_follow_test.py,No exception in execute_script method.,2016-10-10 22:29:50.657883,2016-10-10 22:29:51.355840,0.6979569999999999,"passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py,No exception in execute_script method.,2016-10-10 22:29:51.355951,2016-10-10 22:29:51.983740,0.6277889999999999,"{""result"":100,""resultDesc"":""收藏成功!"",""collectStatus"":""1""}
Traceback (most recent call last):
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py"", line 41, in <module>
    collect_assert(collect_post_test('runcheck5@163.com','1132664','1'))
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py"", line 30, in collect_assert
    tylan_assert(jsonResult['resultDesc'],u""成功"")
  File ""/Users/tylan/Desktop/myAuty/Auty/utils/utils.py"", line 17, in tylan_assert
    print 'failed,actual result:'+str(actual).decode('UTF-8').encode('gbk')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/follow_test.py,No exception in execute_script method.,2016-10-10 22:29:51.983846,2016-10-10 22:29:53.041003,0.057157,"passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/login_test.py,No exception in execute_script method.,2016-10-10 22:29:53.041109,2016-10-10 22:29:53.173767,0.132658,"No login interface.
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/post_info_test.py,No exception in execute_script method.,2016-10-10 22:29:53.173864,2016-10-10 22:29:54.451368,0.277504,"passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/report_test.py,No exception in execute_script method.,2016-10-10 22:29:54.451660,2016-10-10 22:29:54.826872,0.375212,"passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/search_users_test.py,No exception in execute_script method.,2016-10-10 22:29:54.826999,2016-10-10 22:29:55.454651,0.627652,"passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/send_post_test.py,No exception in execute_script method.,2016-10-10 22:29:55.454755,2016-10-10 22:29:56.070240,0.615485,"Traceback (most recent call last):
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/send_post_test.py"", line 36, in <module>
    basic_assert(send_post_test('runcheck5@163.com'))
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/send_post_test.py"", line 32, in basic_assert
    tylan_assert(jsonResult['resultDesc'],u""发帖成功!"")
  File ""/Users/tylan/Desktop/myAuty/Auty/utils/utils.py"", line 17, in tylan_assert
    print 'failed,actual result:'+str(actual).decode('UTF-8').encode('gbk')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/upload_images_test.py,No exception in execute_script method.,2016-10-10 22:29:56.070376,2016-10-10 22:29:56.683717,0.613341,"passed
passed
"
