scriptPath,detail,startTime,endTime,duration,result
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_user_informs_test.py,No exception in execute_script method.,2016-10-11 22:08:02.754238,2016-10-11 22:08:03.441458,0.6872199999999999,"<html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
/circle_getUserInforms.html was not found on this server.
<p /><hr />
<small>
Resin/3.1.14
</small>
</body></html>

Traceback (most recent call last):
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_user_informs_test.py"", line 31, in <module>
    basic_assert(get_user_informs_test('runcheck5@163.com'))
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/get_user_informs_test.py"", line 26, in basic_assert
    jsonResult = json.loads(r.content)
  File ""/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py"", line 338, in loads
    return _default_decoder.decode(s)
  File ""/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py"", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ""/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py"", line 384, in raw_decode
    raise ValueError(""No JSON object could be decoded"")
ValueError: No JSON object could be decoded
"
,Exception in execute_script method: [Errno 2] No such file or directory: '',2016-10-11 22:08:03.441633,2016-10-11 22:08:03.442143,0.0005099999999999999,
