scriptPath,detail,startTime,endTime,duration,result
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/batch_follow_test.py,No exception in execute_script method.,2016-10-10 22:23:45.965799,2016-10-10 22:23:46.609929,0.64413,"passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py,No exception in execute_script method.,2016-10-10 22:23:46.610035,2016-10-10 22:23:47.197336,0.587301,"{""result"":100,""resultDesc"":""收藏成功!"",""collectStatus"":""1""}
failed
passed
Traceback (most recent call last):
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py"", line 41, in <module>
    collect_assert(collect_post_test('runcheck5@163.com','1132664','1'))
  File ""/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/collect_post_test.py"", line 32, in collect_assert
    tylan_assert(collectStatus,'1')
NameError: global name 'collectStatus' is not defined
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/follow_test.py,No exception in execute_script method.,2016-10-10 22:23:47.197454,2016-10-10 22:23:48.257060,0.059606,"passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/login_test.py,No exception in execute_script method.,2016-10-10 22:23:48.257157,2016-10-10 22:23:48.396608,0.139451,"No login interface.
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/post_info_test.py,No exception in execute_script method.,2016-10-10 22:23:48.396726,2016-10-10 22:23:49.022167,0.625441,"passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/report_test.py,No exception in execute_script method.,2016-10-10 22:23:49.022262,2016-10-10 22:23:49.389223,0.366961,"passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/search_users_test.py,No exception in execute_script method.,2016-10-10 22:23:49.389330,2016-10-10 22:23:50.744172,0.354842,"passed
passed
passed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/send_post_test.py,No exception in execute_script method.,2016-10-10 22:23:50.744282,2016-10-10 22:23:51.357586,0.613304,"failed
failed
"
/Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/upload_images_test.py,No exception in execute_script method.,2016-10-10 22:23:51.357780,2016-10-10 22:23:51.955073,0.597293,"passed
passed
"
